# Generated by Django 4.1.1 on 2022-09-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_brand', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo_image')),
            ],
        ),
    ]
