# Generated by Django 4.1.1 on 2022-09-27 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=50)),
                ('hp', models.IntegerField(null=True)),
                ('nm', models.IntegerField(null=True)),
                ('model_photo', models.ImageField(blank=True, null=True, upload_to='model_photo')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=50)),
                ('engine_series', models.CharField(max_length=50)),
                ('hp_series', models.IntegerField(null=True)),
                ('nmL_series', models.IntegerField(null=True)),
                ('series_photo', models.ImageField(blank=True, null=True, upload_to='series_photo')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.model')),
            ],
        ),
    ]
